#  Copyright: (c) 2017-2019 Joshith Rayaroth Koderi
#  This file is part of Wolfinch.
# 
#  Wolfinch is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
# 
#  Wolfinch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with Wolfinch.  If not, see <https://www.gnu.org/licenses/>.
##################################################
# Wolfinch Global config file
##################################################


# Define the interested exchanges here. 
# One primary exchange for trading and as many others in spectator mode
# data from exchanges in spectator mode will be considered for trading decision
exchanges:
   - 'robinhood' : 
      role: 'primary'
      config: 'config/robinhood.yml'
      products:
         - 'INO':
            fund_type: USD
            fund_max_liquidity : 900 #$$               
            fund_max_per_buy_value : 500 #$100 max per buy
            asset_max_per_trade_size: 1000 #per sell asset size max
            asset_min_per_trade_size: 1 #Min asset size to trade with (may come from exch limits or asset limits)
#            stop_loss:
#               enabled: true
#               kind : simple      #simple(default) | trailing | ATRXX | 
#               rate : 4 #-3%
#            take_profit:
#               enabled: true
#               rate: 19 # 10percent
#            decision:
#               model    : simple
#               config   :
#                  strategy: TRABOS
#                  params : {'period': 115, 'ema': 30, 'atr': 165, 'mfi': 200, 'vwap': 200, 'mfi_dir_len': 2, 'obv_dir_len': 2, 'stop_x': 10, 'profit_x': 8, 'vosc_short': 80, 'vosc_long': 150, 'timeout_buy': 0, 'timeout_sell': 0}
      # products - end            
      order_type    : market
      fee     : 
         maker : 0 #make fee %
         taker : 0 #taker fee %
   #cbpro - end
# exchanges - end
# Global Cfg
stop_loss:
   enabled: true
   kind : simple      #simple(default) | trailing | ATRXX | 
   rate : 4 #-3%
take_profit:
   enabled: true
   rate: 19 # 10percent
decision:
   model    : simple
   config   :
      strategy: TATS
      #params : {'period': 115, 'ema': 30, 'atr': 165, 'mfi': 200, 'vwap': 200, 'mfi_dir_len': 2, 'obv_dir_len': 2, 'stop_x': 10, 'profit_x': 8, 'vosc_short': 80, 'vosc_long': 150, 'timeout_buy': 0, 'timeout_sell': 0}
# Global Cfg - end
# TODO: exchanges specific config should follow a common timing, should be driven by global config
candle_interval : 60  # 1 min 

backfill:
   enabled  : true  
   period   : 15  #in Days

simulator:
   enabled : true
   backtesting : true 
   
genetic_optimizer: 
   enabled : false
   N_POP : 10
   N_GEN : 1
   N_MP : 1
   strategy : EMA_DEV
ui:
   #enabled : false
   enabled : true   
   port : 8080
   
#EOF
